### ISSUE TITLE
Write nice readme

### ISSUE THREAD

**Issue by sroehrl** [sroehrl/neoan3-hcapture#1]
Specifically for Hacktoberfest:

I would appreciate help in writing a nice readme for this project. I am not affiliated with hcaptcha in any way.

**Comment by pBouillon** [comment]
Hey !  
Can I take this one if this is not already taken ? I think that I might be able to do something pleasant 😄

**Comment by sroehrl** [comment]
@pBouillon Thank you! The stage is yours: 

Please send PRs from your fork to the readme-branch.

**Comment by rorkyendo** [comment]
> Specifically for Hacktoberfest:
> 
> I would appreciate help in writing a nice readme for this project. I am not affiliated with hcaptcha in any way.

Hey, can i take it for my first test to join fork with others?

**Comment by sroehrl** [comment]
@rorkyendo there is already a pull request in the making by @pBouillon. 
I am not sure what you want to test. Feel free to fork, change & play, but note that this issue is already assigned.

**Comment by BhaskarJoshi-01** [comment]
I want to edit tis.

**Comment by sroehrl** [comment]
@LuciferJoshi I was just about to close this issue as @pBouillon has provided a PR I just merged. Is there something you think should be changed?
